### ISSUE TITLE
Unable to configure the barricade compiler

### ISSUE THREAD

**Issue by ZeeshanShabbir** [mutualmobile/Barricade2#4]
Gradle is unable to resolve the barricade compiler and times out. 

I am adding ksp plugin as follow.

settings.gradle has following added 
```
pluginManagement {
    plugins {
        id("com.google.devtools.ksp") version "1.6.10-1.0.4"
    }
    repositories {
        gradlePluginPortal()
        google()
    }
}
```
and in app module I have included the plugin id. `id("com.google.devtools.ksp") ` and added compiler dependency as `ksp(libs.barricade.compiler)` and gradle times out.  Is there something which I am missing? 

This is the error that I am getting 
```
Unable to find method 'com.google.devtools.ksp.gradle.KspTaskJvm.getClasspathSnapshotProperties()Lorg/jetbrains/kotlin/gradle/tasks/KotlinCompile$ClasspathSnapshotProperties;'
com.google.devtools.ksp.gradle.KspTaskJvm.getClasspathSnapshotProperties()Lorg/jetbrains/kotlin/gradle/tasks/KotlinCompile$ClasspathSnapshotProperties;
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)```

**Comment by shubhamsinghmutualmobile** [comment]
Just to be sure, I did a clean repo clone (for Barricade2) and tried to run the project as it is, and it's working just fine on my system.

Nonetheless, I could find this same issue on the Compose Destinations repo (which also uses KSP internally) with the same error message as yours:
https://github.com/raamcosta/compose-destinations/issues/119

They weren't able to solve it so far 🤷
I'll keep checking for solutions nevertheless and will drop a comment here if I find any (but I'm pretty sure this error is not related to Barricade2 itself).

In the meanwhile, you can try resetting your app to the last point where it was in the working state and check for anything you might've missed.

**Comment by ZeeshanShabbir** [comment]
@shubhamsinghmutualmobile Thank you for your detailed reply. 

Are you sure that `com.mutualmobile:barricade-compiler2:0.0.1` is available to access?  I thought maybe I might some issues in my existing codebase. Created a new project and getting this error. I don't see it on [mavenlibs](https://mavenlibs.com/maven/dependency/com.mutualmobile) as well.

```
 Could not resolve all files for configuration ':app:ksp'.
         > Could not find com.mutualmobile:barricade-compiler2:0.0.1.
           Searched in the following locations:
             - https://dl.google.com/dl/android/maven2/com/mutualmobile/barricade-compiler2/0.0.1/barricade-compiler2-0.0.1.pom
             - https://repo.maven.apache.org/maven2/com/mutualmobile/barricade-compiler2/0.0.1/barricade-compiler2-0.0.1.pom
           Required by:
               project :app
```

**Comment by shubhamsinghmutualmobile** [comment]
@ZeeshanShabbir  Could you try using `com.mutualmobile:barricade-compiler:0.0.1`? Seems like there has been some typo in the Readme, we will fix that asap. Thanks for the information!

**Comment by ZeeshanShabbir** [comment]
oh nvm, thanks :D
