### ISSUE TITLE
Requesting a new release 

### ISSUE THREAD

**Issue by prudhvir3ddy** [mutualmobile/Barricade2#9]
Current release got "random" hardcoded in the library so when updating the UI in barricade config screen, we will get a crash

**Comment by shubhamsinghmutualmobile** [comment]
Done: https://github.com/mutualmobile/Barricade2/releases/tag/v0.0.4 ✅
Could you please check and update here if the library works for you now @prudhvir3ddy?

**Comment by prudhvir3ddy** [comment]
Thanks, working perfectly.
